export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES';

export const ADD_RECIPE = 'ADD_RECIPE';

export const LOAD_VISUALL = 'LOAD_VISUALL';

export const SET_USER_INFO = 'SET_USER_INFO';

export const SET_VISUALL_METADATA = 'SET_VISUALL_METADATA';